### ISSUE TITLE
Fix dockerization of propromo core.

### ISSUE THREAD

**Issue by jonasfroeller** [propromo-software/propromo.php#254]
1. create a Dockerfile that successfully serves propromo-core
2. create a CI workflow that releases + deploys the docker image
   - build on every commit
   - release if on main (individual `job`)
     - publish the docker image
     - create a commit in the GitOps repo to update the image
       (see https://github.com/alex-brot/alex-brot-shop/blob/main/.github/workflows/build-and-deploy-prod.yaml for an example)

**Comment by SIMULATAN** [comment]
According to https://github.com/orgs/community/discussions/25702, actions are only triggered when the push wasn't done with a github actions token. Looking at https://github.com/propromo-software/propromo/actions/workflows/docker-ci.yml, that checks out. @jonasfroeller do we have an account to create a PAT to do the tagging with?

**Comment by propro-mo** [comment]
@SIMULATAN 

https://github.com/propro-mo.  
I am sending you the credentials.

**Comment by SIMULATAN** [comment]
The CI works now. pushing that thing onto k8s is tracked in #256
