### ISSUE TITLE
Error on Registration

### ISSUE THREAD

**Issue by Stenz123** [propromo-software/propromo.php#255]
**Describe the bug**
When Registering a new User the Page throws the Error `Seems like something went wrong... The password field is required. (and 1 more error)` 

**To Reproduce**
Register a new User

**Expected behavior**
Register Successfully

**Screenshots**
[i.imgur.com/jbzcITW.png](https://i.imgur.com/jbzcITW.png)

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Browser: Firefox

**Comment by jonasfroeller** [comment]
cannot reproduce

**Comment by Stenz123** [comment]
Please reopen, this error occurs if the password is to long. An appropriate error message should be shown

**Comment by jonasfroeller** [comment]
@stevan06v
