### ISSUE TITLE
Kubernetes cluster for propromo.

### ISSUE THREAD

**Issue by jonasfroeller** [propromo-software/propromo.php#256]
- [x] move github microservice
- [ ] switch propromo.rest postgres URL to propromo k8s postgres

**Comment by SIMULATAN** [comment]
@jonasfroeller currently, the leocloud doesn't permit multiple subdomains per user. hence, we must use a subpath. is there a way to set that in the microservice?

**Comment by jonasfroeller** [comment]
@SIMULATAN There shouldn't be any collision, it is just `/v1/\<adapter_name\>`.

**Comment by SIMULATAN** [comment]
Since you have way more experience, could anyone verify the functionality?
Everything should be working now, the rest microservice still uses the neon-hosted postgres though

**Comment by jonasfroeller** [comment]
https://github.com/propromo-software/propromo.ops
