### ISSUE TITLE
As a user, I want to gain access to a Kubernetes deployment in Leocloud, so that I can manage and monitor my application, ensuring it runs smoothly and efficiently.

### ISSUE THREAD

**Issue by stevan06v** [propromo-software/propromo.php#276]
- The user must have secure access to the Kubernetes cluster deployed in Leocloud.

- Proper authentication and authorization mechanisms (e.g., RBAC) should be set up to control access.

**Comment by SIMULATAN** [comment]
@stevan06v the application is alive,  the only thing needed now is some manual intervention in order to create the necessary tables (aka run the migration scripts).

**Comment by SIMULATAN** [comment]
worx
