### ISSUE TITLE
As a project owner I want to see how the project will look like and how it will work.

### ISSUE THREAD

**Issue by jonasfroeller** [propromo-software/propromo.php#4]
row wireframe: https://www.figma.com/file/hGhH8vVtF7gOmIv5DPXd65/Propromo---Project-Progress-Tracker?type=design&node-id=0%3A1&mode=design&t=Ja2XdVHtXHKZjTHs-1

**Comment by stevan06v** [comment]
Given: I want to get an idea of the project and the design of the website in general
When: I open the PDF-Files
Then: I get the perfect overview and understanding of how the software will look and act like
